# References
# https://github.com/bitnami/containers/blob/main/bitnami/spark/docker-compose.yml
# https://github.com/bitnami/containers/blob/main/bitnami/cassandra/docker-compose.yml

# Spark Standalone Mode > Cluster Launch Scripts
# https://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts

services:
  spark-master:
    image: bitnami/spark:3.5.0
    ports:
      - 9090:9090
      - 7077:7077
    environment:
      SPARK_MODE: master
      SPARK_MASTER_WEBUI_PORT: 9090
      SPARK_PUBLIC_DNS: "${SPARK_IP_ADDRESS:-localhost}"
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark

  spark-worker-1:
    image: bitnami/spark:3.5.0
    ports:
      - 9191:9191
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 9191
      SPARK_PUBLIC_DNS: "${SPARK_IP_ADDRESS:-localhost}"
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.5.0
    ports:
      - 9192:9192
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 9192
      SPARK_PUBLIC_DNS: "${SPARK_IP_ADDRESS:-localhost}"
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    depends_on:
      - spark-master

  spark-history-server:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
    ports:
      - 18080:18080
    volumes:
      - ${SPARK_MODULE_PATH:-.}/spark-history-server-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - spark-history-server-events:/opt/bitnami/spark/events
    environment:
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2

  cassandra-node-1:
    image: bitnami/cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/bitnami
    environment:
      CASSANDRA_CLUSTER_NAME: "Kafka Labs"
      CASSANDRA_DATACENTER: datacenter1
      CASSANDRA_SEEDS: cassandra-node-1
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra

volumes:
  spark-history-server-events:
    driver: local
  cassandra-data:
    driver: local
