# References
# https://github.com/bitnami/containers/blob/main/bitnami/spark/docker-compose.yml
# https://github.com/bitnami/containers/blob/main/bitnami/cassandra/docker-compose.yml

# Spark Standalone Mode > Cluster Launch Scripts
# https://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts

services:
  spark-master:
    image: bitnami/spark:3.5.0
    ports:
      - 9090:9090
      - 7077:7077
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=9090
      - SPARK_PUBLIC_DNS=${SPARK_IP_ADDRESS:-{{ host }}}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  spark-worker:
    image: bitnami/spark:3.5.0
    ports:
      - 9091:9091
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=9091
      - SPARK_PUBLIC_DNS=${SPARK_IP_ADDRESS:-{{ host }}}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master

  spark-history-server:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
    ports:
      - 18080:18080
    volumes:
      - ${SPARK_MODULE_PATH:-.}/spark-history-server-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - spark-history-server-events:/opt/bitnami/spark/events
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master
      - spark-worker

  cassandra:
    image: bitnami/cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/bitnami
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

volumes:
  spark-history-server-events:
    driver: local
  cassandra-data:
    driver: local
