all:
  hosts:
    ${kafka_private_ip}:
      ansible_connection: ssh
      ansible_host: ${kafka_private_ip}
      ansible_user: ${ssh_username}
      ansible_ssh_private_key_file: ${ssh_private_key_file}

remote:
  hosts:
    ${kafka_private_ip}:
