all:
  hosts:
    ${kafka_ip_address}:
      ansible_connection: ssh
      ansible_host: ${kafka_ip_address}
      ansible_user: ${ssh_username}
      ansible_ssh_private_key_file: ${ssh_key_file}

remote:
  hosts:
    ${kafka_ip_address}:
