# ngrok Agent Configuration File
# https://ngrok.com/docs/agent/config/

version: "2"
authtoken: "{{ ngrok_token }}"

tunnels:
  akhq:
    proto: http
    addr: 8080

  control-center:
    proto: http
    addr: 9021

  kafka:
    proto: tcp
    addr: 9092
